base_url = "https://linshiqi.github.io/blog"
title = "Shiqi's Blog"
theme = "deepthought"
default_language = "zh"

[markdown]
[markdown.highlighting]
render = true
theme = "catppuccin-mocha"

[extra]
# 必须定义为这种“语言包”嵌套格式
navbar_items = [
    { code = "zh", nav_items = [
        { name = "首页", url = "/" },
        { name = "博客", url = "/blog" },
        { name = "关于", url = "/about" }
    ]},
    { code = "en", nav_items = [
        { name = "Home", url = "/" },
        { name = "Blog", url = "/blog" }
    ]}
]

[extra.author]
name = "Shiqi Lin"

[extra.social]
# github = "https://github.com/linshiqi"

# 基础显示开关
show_all_posts = true
show_date = true